ConduitPlatform/Conduit-UI

- src/components/common/sharedClasses.ts
- src/components/forms/EditableForm.tsx
- src/components/sms/SendSms.tsx
- src/components/storage/StorageAddDrawer.tsx
- src/components/storage/StorageConfig.tsx
- src/components/storage/StorageTable.tsx
- src/http/SmsRequests.ts
- src/models/sms/SmsModels.ts
- src/models/storage/StorageModels.ts
- src/redux/slices/smsSlice.ts
- src/redux/slices/storageSlice.ts
```
Inludes many changes such as: 
- Sms is now on hook form and it sends the data to the appropriate request
- We can delete folders inside storage 
- We no longer see the previously uploaded file when we are about to upload a new one
- Added an option for local provider on storage config
- Email field on forms in now  a dropdown menu including all form fields that are of type string
...
Please delete options that are not relevant.
```
> UI inconsistencies

- src/components/emails/SendEmailForm.tsx
- src/components/emails/TemplateForm.tsx
- src/components/payments/Forms/CustomerForm.tsx
- src/pages/email/templates.tsx
> fix(templateform, customerForm): types

- src/components/forms/ViewEditForm.tsx
- src/pages/forms/view.tsx
```
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
...
Please delete options that are not relevant.
```
> fix: forms forward to field and drawer image

- src/components/authentication/AuthAccordion.tsx
- src/models/emails/EmailModels.ts
- src/redux/slices/emailsSlice.ts
Added redirect uri to google and facebook sign in methods and removed apiUser from sendgrid configuration (emails)
> Sign in methods fixes

- src/components/authentication/AuthUsers.tsx
- src/components/common/DataTableActions.tsx
- src/components/common/Paginator.tsx
- src/components/modules/Modules.tsx
- src/components/navigation/CustomListItem.tsx
- src/components/navigation/Drawer.tsx
- src/components/payments/ViewSubscription.tsx
- src/components/storage/StorageFiles.tsx
- src/pages/authentication/users.tsx
- src/pages/cms/schemas/index.tsx
- src/pages/email/templates.tsx
- src/pages/forms/view.tsx
- src/pages/index.tsx
- src/pages/payments/customers.tsx
- src/pages/payments/products.tsx
- src/pages/payments/subscriptions.tsx
- src/pages/payments/transactions.tsx
- src/theme/index.ts
> fix(theming): changed look of theming mainly focused on paper

- src/components/database/custom-endpoints/EndpointInputs.tsx
> fix(EndpointInputs): get operation can no longer accept body params

- src/components/authentication/AuthenticationConfig.tsx
- src/components/chat/ChatRoomPanel.tsx
- src/components/chat/ChatRoomTab.tsx
- src/components/chat/ChatRooms.tsx
- src/components/common/DataTable.tsx
- src/components/database/custom-endpoints/EndpointsList.tsx
- src/components/database/schemas/SchemaDataHeader.tsx
> Styling improvements

- src/components/authentication/AddUserDrawerContent.tsx
- src/components/authentication/ServiceAccountsTabs.tsx
- src/components/database/custom-endpoints/Sidelist.tsx
- src/components/database/schemas/Schemas.tsx
- src/components/emails/ExternalTemplates.tsx
- src/components/forms/EditableForm.tsx
- src/components/settings/CoreSettingsTab.tsx
- src/components/settings/SdksTab.tsx
- src/components/settings/SecretsDialog.tsx
- src/components/settings/SecretsTab.tsx
- src/pages/login.tsx
Styling improvements on various pages(Secrets, clientsSDK, core, serviceAccounts), fixes on Select components where the label was in the way of the Select field.
> Styling fixes

- src/components/authentication/AddUserDrawerContent.tsx
- src/components/authentication/EditUserDialog.tsx
- src/http/AuthenticationRequests.ts
> Authentication fixes

- apps/Conduit-UI/src/pages/index.tsx
refactor: fix swagger/graphql links
> refactor: fix conduit documentation links

- apps/Conduit-UI/src/components/database/schemas/GroupTypeChildViewer.tsx
- apps/Conduit-UI/src/components/database/schemas/GroupTypeViewer.tsx
- apps/Conduit-UI/src/components/database/schemas/Introspection/IntrospectionLayout.tsx
- apps/Conduit-UI/src/components/database/schemas/Introspection/IntrospectionModal.tsx
- apps/Conduit-UI/src/components/database/schemas/Introspection/IntrospectionSchemasList.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaOverview.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaViewer.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/authenticationLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/chatLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/databaseLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/emailsLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/formsLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/notificationLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/paymentsLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/securityLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/settingsLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/smsLayout.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/storageLayout.tsx
- apps/Conduit-UI/src/http/IntrospectionRequests.ts
- apps/Conduit-UI/src/models/database/CmsModels.ts
- apps/Conduit-UI/src/pages/database/introspection.tsx
- apps/Conduit-UI/src/redux/slices/databaseSlice.ts
- apps/Conduit-UI/src/utils/ExtractSchemaInfo.tsx
Introspection section on database, where users can add (and edit before doing so) their own schemas.
> Introspection UI

- apps/Conduit-UI/src/redux/slices/securitySlice.ts
> fix(alias): now an optional property updating client

- apps/Conduit-UI/src/components/storage/StorageConfig.tsx
- apps/Conduit-UI/src/models/storage/StorageModels.ts
- apps/Conduit-UI/src/redux/slices/storageSlice.ts
support https://github.com/ConduitPlatform/Conduit/issues/194
waiting https://github.com/ConduitPlatform/Conduit/pull/199
> feat(storage): support aliyun oss config

- apps/Conduit-UI/src/redux/slices/storageSlice.ts
> fix(build): defaults provider to local on  storage initialization

- apps/Conduit-UI/src/components/database/schemas/Introspection/IntrospectionLayout.tsx
- apps/Conduit-UI/src/redux/slices/databaseSlice.ts
- libraries/ui-components/src/components/navigation/sharedLayout.tsx
While introspection is underway, we now show the loading indicator. After introspection finishes, we fetch the newly introspected schemas.
Also a styling fix regarding the loading animation.
> fix(introspection): loading

- apps/Conduit-UI/src/components/database/custom-endpoints/InfiniteScrollList.tsx
- apps/Conduit-UI/src/components/database/schemas/EditSchema/Header.tsx
- apps/Conduit-UI/src/components/database/schemas/EditSchema/PermissionsDialog.tsx
- apps/Conduit-UI/src/components/navigation/Drawer.tsx
- apps/Conduit-UI/src/theme/index.ts
- apps/Conduit-UI/src/utils/ExtractSchemaInfo.tsx
- libraries/ui-components/src/components/navigation/ModuleItem.tsx
Changed permissions and its' sub-components naming in the schema editor as it was confusing.
Improved the contrast text of the primary palette color.
> Permissions naming fixes

- apps/Conduit-UI/package.json
- apps/Conduit-UI/src/components/navigation/Layout.tsx
- apps/Conduit-UI/src/createEmotionCache.ts
- apps/Conduit-UI/src/pages/_app.tsx
- apps/Conduit-UI/src/pages/_document.tsx
- yarn.lock
material-ui with next, home button in background fix
> fix(Conduit-UI): server-side css

- apps/Conduit-UI/package.json
- package.json
- yarn.lock
> feat: turborepo build & dev pipelines

- apps/Conduit-UI/src/components/settings/ChangePasswordTab.tsx
- apps/Conduit-UI/src/components/settings/GeneralSettingsTab.tsx
- apps/Conduit-UI/src/http/requests/SettingsRequests.ts
- apps/Conduit-UI/src/redux/slices/settingsSlice.ts
fix(settings): change password using plaintext for old pass
> fix(settings): change password using wrong endpoint

- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/styledLayout.tsx
- libraries/ui-components/src/components/GraphQLModal.tsx
> fix: swagger and graphql modal urls

- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
- apps/Conduit-UI/src/components/logs/LogsList.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/sharedLayout.tsx
- apps/Conduit-UI/src/models/logs/LogsModels.ts
logs component to drawer, logs to home
> Logs drawer

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
logs open drawer with title press, styles
> feat: logs open drawer with title press

- apps/Conduit-UI/src/http/requestsConfig.ts
- apps/Conduit-UI/src/pages/_app.tsx
- apps/Conduit-UI/src/redux/slices/appAuthSlice.ts
Support for JWT was dropped so we changed the JTW token prefix to Bearer.
> fix(Tokens): changed JWT to Bearer token as support was dropped

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
- apps/Conduit-UI/src/http/requests/LogsRequests.ts
- apps/Conduit-UI/src/redux/slices/LogsSlice.ts
> fix: remove instance from logs

- apps/Conduit-UI/src/components/chat/CreateChatRoomDrawer.tsx
- apps/Conduit-UI/src/components/emails/EmailTemplates.tsx
- apps/Conduit-UI/src/components/forms/FormsView.tsx
- apps/Conduit-UI/src/http/requests/AuthenticationRequests.ts
- apps/Conduit-UI/src/http/requests/ChatRequests.ts
- apps/Conduit-UI/src/http/requests/CustomEndpointsRequests.ts
- apps/Conduit-UI/src/http/requests/DatabaseRequests.ts
- apps/Conduit-UI/src/http/requests/EmailRequests.ts
- apps/Conduit-UI/src/http/requests/FormsRequests.ts
- apps/Conduit-UI/src/http/requests/IntrospectionRequests.ts
- apps/Conduit-UI/src/http/requests/SettingsRequests.ts
- apps/Conduit-UI/src/http/requests/StorageRequests.ts
- apps/Conduit-UI/src/redux/slices/emailsSlice.ts
change parameters of requests 
> fix: parameters of requests

- apps/Conduit-UI/src/http/requestsConfig.ts
> fix: prometheus url

- apps/Conduit-UI/src/utils/validations.ts
> fix: phone number regular expression

- apps/Conduit-UI/src/components/chat/ChatRoomMessages.tsx
- apps/Conduit-UI/src/components/chat/ChatRoomPanel.tsx
- apps/Conduit-UI/src/components/chat/ChatRoomTab.tsx
- apps/Conduit-UI/src/components/chat/ChatRoomTabs.tsx
> fix: chat styles

- apps/Conduit-UI/src/components/chat/ChatRoomBubble.tsx
- apps/Conduit-UI/src/http/requests/ChatRequests.ts
- apps/Conduit-UI/src/models/chat/ChatModels.ts
change chat request populate field, chat message user
> fix: chat request populate field, chat message user

- apps/Conduit-UI/src/components/charts/AreaChart.tsx
- apps/Conduit-UI/src/components/metrics/ExtractMetricGraph.tsx
- apps/Conduit-UI/src/components/metrics/TotalRequestsByModule.tsx
- apps/Conduit-UI/src/components/navigation/Drawer.tsx
modules refresh button, refactor metrics graph to component
> feat: modules refresh button

- apps/Conduit-UI/src/components/modules/Modules.tsx
- apps/Conduit-UI/src/redux/slices/appSlice.ts
- apps/Conduit-UI/src/utils/useNotifier.ts
snackbar duplicate messages when clicking non-serving module
> fix: disabled module duplicate snackbar

- apps/Conduit-UI/src/components/authentication/SignInMethod.tsx
- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/metrics/ExtractMetricGraph.tsx
- apps/Conduit-UI/src/hooks/useIsMounted.ts
- apps/Conduit-UI/src/http/requests/FormsRequests.ts
- apps/Conduit-UI/src/theme/global.css
This PR solves the issues below:
- An issue on home where 404 notifications were present to due the fact that non-active module endpoints were used.
- State updates on unmounted components present on home fixes with  useIsMounted hook
- Scrollbar improvements
- Updating forms now works as expected
- Proper fetching of admin users
> Error fixes

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
- apps/Conduit-UI/src/redux/slices/metricsSlice.ts
logs component filter buttons responsiveness at sm
> fix: logs component responsiveness

- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/metrics/RequestLatency.tsx
- apps/Conduit-UI/src/http/requests/MetricsRequests.ts
- apps/Conduit-UI/src/redux/slices/metricsSlice.ts
This pr fixes an issue where the homescreen latency defaulted to 0.
> fix(Latency): Home latency fix

- apps/Conduit-UI/src/redux/slices/storageSlice.ts
> fix: storage viewpager issue

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
> fix: logs component drag issue

- apps/Conduit-UI/next.config.js
- apps/Conduit-UI/src/components/modules/moduleUtils.tsx
This PR includes a bugfix. Clicking on settings page displayed an error claiming it as a disabled module.
> fix(settings): fixed a bug where settings page was not accessible

- apps/Conduit-UI/src/components/navigation/Layout.tsx
> fix: removed settings page loader

- apps/Conduit-UI/src/components/common/ThemeSwitch.tsx
- apps/Conduit-UI/src/components/logs/LogsList.tsx
- apps/Conduit-UI/src/components/modules/Modules.tsx
- apps/Conduit-UI/src/components/modules/moduleUtils.tsx
- apps/Conduit-UI/src/components/navigation/Drawer.tsx
- libraries/ui-components/src/components/navigation/ModuleItem.tsx
> refactor: drawer fixes

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
close logs component by clicking title
> feat: close logs component by clicking title

- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/modules/Modules.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/sharedLayout.tsx
- apps/Conduit-UI/src/http/requestsConfig.ts
- apps/Conduit-UI/src/pages/api/[...path].ts
- apps/Conduit-UI/src/redux/slices/appAuthSlice.ts
- apps/Conduit-UI/src/redux/slices/appSlice.ts
hide logs, metrics if loki and prometheus have not been set
> feat: Logs metrics availability

- apps/Conduit-UI/src/components/authentication/AuthenticationConfig.tsx
- apps/Conduit-UI/src/components/database/DatabaseDashboard.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/CustomEndpointsLayout.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/OperationSection.tsx
- apps/Conduit-UI/src/components/database/schemas/EditSchema/Header.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaEditor.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/NewSchemaDialog.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaOverview.tsx
- apps/Conduit-UI/src/components/database/schemas/Schemas.tsx
- apps/Conduit-UI/src/http/requests/DatabaseRequests.ts
- apps/Conduit-UI/src/pages/database/custom.tsx
- apps/Conduit-UI/src/redux/slices/databaseSlice.ts
This PR includes the following:
- System schemas cannot be edited
- New schemas cannot take reserved system schemas names
- New way to pass permissions and crudOperations on create and patch schemas
- New way to receive available from backend (for custom endpoints)
> Database rework

- apps/Conduit-UI/src/redux/slices/databaseSlice.ts
fix database delete schema counter
> fix: delete schema counter

- apps/Conduit-UI/src/components/authentication/AuthenticationConfig.tsx
- apps/Conduit-UI/src/components/authentication/ServiceAccountsTabs.tsx
- apps/Conduit-UI/src/components/chat/ChatConfig.tsx
- apps/Conduit-UI/src/components/common/JsonEditorComponent.tsx
- apps/Conduit-UI/src/components/emails/EmailConfig.tsx
- apps/Conduit-UI/src/components/forms/EditableForm.tsx
- apps/Conduit-UI/src/components/forms/FormsConfig.tsx
- apps/Conduit-UI/src/components/notifications/NotificationConfig.tsx
- apps/Conduit-UI/src/components/routing/SecurityTab.tsx
- apps/Conduit-UI/src/components/routing/routerSettings.tsx
- apps/Conduit-UI/src/components/settings/GeneralSettingsTab.tsx
- apps/Conduit-UI/src/components/sms/SendSms.tsx
- apps/Conduit-UI/src/components/sms/SmsConfig.tsx
- apps/Conduit-UI/src/components/storage/StorageConfig.tsx
configs tooltip styles and button styles
> feat: UI consistency

- apps/Conduit-UI/src/components/authentication/AuthenticationDashboard.tsx
- apps/Conduit-UI/src/components/chat/ChatDashboard.tsx
- apps/Conduit-UI/src/components/database/DatabaseDashboard.tsx
- apps/Conduit-UI/src/components/emails/EmailDashboard.tsx
- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/metrics/LottieForWidget.tsx
- apps/Conduit-UI/src/components/metrics/MetricsWidgetSkeleton.tsx
- apps/Conduit-UI/src/components/metrics/TotalRequestsByModule.tsx
- apps/Conduit-UI/src/components/metrics/getLottieByTitle.ts
- apps/Conduit-UI/src/components/navigation/Drawer.tsx
- apps/Conduit-UI/src/components/routing/RouterDashboard.tsx
- apps/Conduit-UI/src/components/storage/StorageAddDrawer.tsx
- apps/Conduit-UI/src/components/storage/StorageCreateDrawer.tsx
- apps/Conduit-UI/src/utils/validations.ts
This PR includes the following:
- Validation for empty string when creating storage container, folders, files
- Cannot proceed with file creating when no file is uploaded
- Remove lottie-file props as it was causing console errors
- Capitalization on Metric Dashboards
> fix(Storage, Metrics): required fields, capitalization

- apps/Conduit-UI/src/components/InfiniteScrollLayout.tsx
- apps/Conduit-UI/src/components/authentication/SignInContainer.tsx
- apps/Conduit-UI/src/components/database/schemas/Introspection/IntrospectionLayout.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaOverview.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaViewer.tsx
- apps/Conduit-UI/src/components/database/schemas/Schemas.tsx
- apps/Conduit-UI/src/components/metrics/MetricCount.tsx
- apps/Conduit-UI/src/components/modules/Modules.tsx
- libraries/ui-components/src/components/navigation/ModuleItem.tsx
fix double scollers, sign in containers tooltip color
> fix: UI fixes

- apps/Conduit-UI/src/components/authentication/EditUserDialog.tsx
- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
- apps/Conduit-UI/src/components/metrics/ModuleHealth.tsx
- apps/Conduit-UI/src/components/navigation/InnerLayouts/sharedLayout.tsx
- apps/Conduit-UI/src/redux/slices/metricsSlice.ts
- apps/Conduit-UI/src/theme/index.ts
This PR focuses mainly on styling improvements: 
- Contrast color of primary is now black
- Swagger, graphQL, documentation buttons moved to the right
- Logs component now expands to full height when clicking on the right arrow
- Edit user dialog now has once again icons, hooray!
> Styling changes

- apps/Conduit-UI/src/components/database/types/BooleanType/BooleanForm.tsx
- apps/Conduit-UI/src/components/database/types/EnumType/EnumForm.tsx
- apps/Conduit-UI/src/components/database/types/GroupType/GroupForm.tsx
- apps/Conduit-UI/src/components/database/types/JSONType/JSONForm.tsx
- apps/Conduit-UI/src/components/database/types/ObjectIdType/ObjectIdForm.tsx
- apps/Conduit-UI/src/components/database/types/RelationType/RelationForm.tsx
- apps/Conduit-UI/src/components/database/types/SimpleType/SimpleForm.tsx
- apps/Conduit-UI/src/components/metrics/ModuleHealth.tsx
- apps/Conduit-UI/src/models/database/BuildTypesModels.ts
This PR makes editing enums more concise, with an add enum textField for new enums, and delete buttons for existing enums inside a Chip component.
> fix(Enums): restructured enum field editing

- apps/Conduit-UI/src/components/logs/LogsComponent.tsx
- apps/Conduit-UI/src/components/logs/LogsList.tsx
fix logs list scroll to bottom
> fix: logs list scroll to bottom

- apps/Conduit-UI/src/components/authentication/AuthenticationDashboard.tsx
- apps/Conduit-UI/src/components/chat/ChatDashboard.tsx
- apps/Conduit-UI/src/components/database/DatabaseDashboard.tsx
- apps/Conduit-UI/src/components/emails/EmailDashboard.tsx
- apps/Conduit-UI/src/components/forms/FormsDashboard.tsx
- apps/Conduit-UI/src/components/metrics/MetricCount.tsx
- apps/Conduit-UI/src/components/metrics/MetricsWidget.tsx
- apps/Conduit-UI/src/components/metrics/ModuleHealth.tsx
- apps/Conduit-UI/src/components/metrics/RequestLatency.tsx
- apps/Conduit-UI/src/components/notifications/NotificationDashboard.tsx
- apps/Conduit-UI/src/components/routing/RouterDashboard.tsx
- apps/Conduit-UI/src/components/sms/SmsDashboard.tsx
- apps/Conduit-UI/src/components/storage/StorageDashboard.tsx
fix metrics cards sizes and spacing
> fix: Metrics cards sizes and spacing

- apps/Conduit-UI/src/components/storage/StorageFiles.tsx
- apps/Conduit-UI/src/components/storage/StorageTable.tsx
- apps/Conduit-UI/src/models/storage/StorageRequestsModels.ts
- apps/Conduit-UI/src/redux/slices/storageSlice.ts
- libraries/ui-components/src/components/DataTableRows.tsx
> feat: storage search

- apps/Conduit-UI/src/http/requestsConfig.ts
fix loki and prometheus 401 error logout issue
> fix: Logout issue

- apps/Conduit-UI/src/pages/api/[...path].ts
- apps/Conduit-UI/src/redux/slices/appAuthSlice.ts
fix logout issue with snackbar and dashboard appearance, proxy on error
> fix: issues

- apps/Conduit-UI/src/redux/slices/settingsSlice.ts
fix new password instead of old and the reverse
> fix: change admin password old-new issue

- apps/Conduit-UI/src/components/database/schemas/SchemaEditor.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/NewSchemaDialog.tsx
- apps/Conduit-UI/src/components/database/schemas/SchemaOverview/SchemaOverview.tsx
This PR includes the following fixes:
- When a schema is being deleted, the url changes accordingly
- New url param for newly created Schemas, to distinguish them from existing ones
> fix(Schemas): Schema editing improvements

- apps/Conduit-UI/src/components/authentication/AddUserDrawer.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/AssignmentsSection.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/CustomEndpointsLayout.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/CustomQueryRow.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/EndpointQueries.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/InputsSection.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/OperationSection.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/QueriesSection.tsx
- apps/Conduit-UI/src/redux/slices/customEndpointsSlice.ts
- apps/Conduit-UI/src/utils/cms.ts
This PR helps with the accessible fields each Schema exposes to custom-endpoints.
> fix(custom-endpoints): stability fixes

- apps/Conduit-UI/src/utils/cms.ts
> fix(custom-endpoints): assignments check that allows setting ObjectId to Relation type

- apps/Conduit-UI/src/components/InfiniteScrollLayout.tsx
- apps/Conduit-UI/src/components/common/TableDialog.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/CustomQueryRow.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/EndpointAssignments.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/MainContent.tsx
- apps/Conduit-UI/src/components/database/custom-endpoints/OperationSection.tsx
- apps/Conduit-UI/src/components/routing/RouterDashboard.tsx
- apps/Conduit-UI/src/utils/cms.ts
- libraries/ui-components/src/components/DataTable.tsx
- libraries/ui-components/src/components/DataTableRows.tsx
This PR is mainly focused on improving Custom Endpoints.
> fix(App): General qol fixes

- apps/Conduit-UI/src/components/database/custom-endpoints/MainContent.tsx
- apps/Conduit-UI/src/utils/cms.ts
A couple more issues fixed on the Custom Endpoints.
> fix(custom-endpoints): Minor Custom Endpoints fixes

- apps/Conduit-UI/src/components/notifications/NotificationConfig.tsx
- apps/Conduit-UI/src/models/notifications/NotificationModels.ts
- apps/Conduit-UI/src/redux/slices/notificationsSlice.ts
> feat(push-notifications): oneSignal support

- apps/Conduit-UI/src/components/authentication/AddUserDrawer.tsx
- apps/Conduit-UI/src/components/chat/ChatConfig.tsx
- apps/Conduit-UI/src/components/common/TableDialog.tsx
- apps/Conduit-UI/src/components/database/types/BooleanType/BooleanForm.tsx
- apps/Conduit-UI/src/components/database/types/BooleanType/BooleanType.tsx
- apps/Conduit-UI/src/components/database/types/EnumType/EnumForm.tsx
- apps/Conduit-UI/src/components/database/types/EnumType/EnumType.tsx
- apps/Conduit-UI/src/components/database/types/EnumType/EnumTypeViewer.tsx
- apps/Conduit-UI/src/components/database/types/GroupType/GroupForm.tsx
- apps/Conduit-UI/src/components/database/types/JSONType/JSONForm.tsx
- apps/Conduit-UI/src/components/database/types/JSONType/JSONType.tsx
- apps/Conduit-UI/src/components/database/types/ObjectIdType/ObjectIdType.tsx
- apps/Conduit-UI/src/components/database/types/RelationType/RelationForm.tsx
- apps/Conduit-UI/src/components/database/types/RelationType/RelationType.tsx
- apps/Conduit-UI/src/components/database/types/SimpleType/SimpleForm.tsx
- apps/Conduit-UI/src/components/database/types/SimpleType/SimpleType.tsx
- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/settings/SettingsAdmins.tsx
- apps/Conduit-UI/src/http/requests/MetricsRequests.ts
- apps/Conduit-UI/src/models/chat/ChatModels.ts
- apps/Conduit-UI/src/redux/slices/chatSlice.ts
- apps/Conduit-UI/src/theme/index.ts
- libraries/ui-components/src/components/ConfirmationDialog.tsx
This PR includes a number of fixes/improvements such:
- removal of strict validation rules for creating a user via the UI
- new user form (authentication) is no longer prefilled with admin credentials from the browser
- admins can no longer delete themselves
- more chat room config options 
- an issue where home health was shown as critical
- schema editor fixes: wrong placeholders, disabling of field name field for existing ones, removal of required field descriptions, styling improvements / refactors
If adding a **new feature**, the PR's …
> fix: global fixes

- apps/Conduit-UI/src/components/metrics/MetricCount.tsx
- apps/Conduit-UI/src/http/requests/MetricsRequests.ts
Metrics fixes from #203, sans-auth-logic.
> fix(metrics): health status displaying critical on missing data, prometheus job

- apps/Conduit-UI/src/components/charts/AreaChart.tsx
- apps/Conduit-UI/src/pages/_document.tsx
- apps/Conduit-UI/src/theme/index.ts
- libraries/ui-components/src/components/navigation/ModuleItem.tsx
> feat: use Inter font

- apps/Conduit-UI/src/features/database/components/schemas/GroupTypeChildViewer.tsx
- apps/Conduit-UI/src/features/database/components/schemas/GroupTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/schemas/Introspection/IntrospectionModal.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/SchemaOverview.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/SchemaViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/BooleanType/BooleanType.tsx
- apps/Conduit-UI/src/features/database/components/types/BooleanType/BooleanTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/EnumType/EnumType.tsx
- apps/Conduit-UI/src/features/database/components/types/EnumType/EnumTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/GroupType/GroupType.tsx
- apps/Conduit-UI/src/features/database/components/types/GroupType/GroupTypeChild.tsx
- apps/Conduit-UI/src/features/database/components/types/JSONType/JSONType.tsx
- apps/Conduit-UI/src/features/database/components/types/JSONType/JSONTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/ObjectIdType/ObjectIdType.tsx
- apps/Conduit-UI/src/features/database/components/types/ObjectIdType/ObjectIdTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/RelationType/RelationType.tsx
- apps/Conduit-UI/src/features/database/components/types/RelationType/RelationTypeViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/SimpleType/SimpleType.tsx
- apps/Conduit-UI/src/features/database/components/types/SimpleType/SimpleTypeViewer.tsx
This PR inc includes the following changes"
- Way cleaner code for the Schema viewer
- UI improvement (better alignment, looks similar to the rest of our design language)
- Some schema editor refactors
> refactor(schema viewer): updated looks and code clenup

- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/BuildTypesContent.tsx
- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/BuildTypesList.tsx
- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/CrudOperationsDialog.tsx
- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/Header.tsx
- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/PermissionsDialog.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaEditor.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/NewSchemaDialog.tsx
- apps/Conduit-UI/src/features/database/components/types/GroupType/GroupType.tsx
- apps/Conduit-UI/src/features/database/components/types/GroupType/GroupTypeChild.tsx
This PR focuses on styling the Schema Editor in a way that it keeps it up to date with the rest of the UI design language.
> refactor: Schema editor styling improvements

- libraries/ui-components/src/components/DataTableRows.tsx
> fix: Storage fix navigation

- apps/Conduit-UI/next.config.js
- apps/Conduit-UI/src/components/home/Home.tsx
- apps/Conduit-UI/src/components/metrics/ExtractMetricGraph.tsx
- apps/Conduit-UI/src/components/metrics/MetricCount.tsx
- apps/Conduit-UI/src/components/metrics/MultipleMetricGraph.tsx
- apps/Conduit-UI/src/features/authentication/components/AuthenticationDashboard.tsx
- apps/Conduit-UI/src/features/chat/components/ChatDashboard.tsx
- apps/Conduit-UI/src/features/database/components/DatabaseDashboard.tsx
- apps/Conduit-UI/src/features/emails/components/EmailDashboard.tsx
- apps/Conduit-UI/src/features/forms/components/FormsDashboard.tsx
- apps/Conduit-UI/src/features/router/components/RouterDashboard.tsx
- apps/Conduit-UI/src/features/sms/components/SmsDashboard.tsx
- apps/Conduit-UI/src/features/storage/components/StorageDashboard.tsx
- apps/Conduit-UI/src/http/requests/LogsRequests.ts
- apps/Conduit-UI/src/http/requests/MetricsRequests.ts
- apps/Conduit-UI/src/http/requestsConfig.ts
- apps/Conduit-UI/src/models/metrics/metricsModels.ts
- apps/Conduit-UI/src/utils/injectMetricsLabels.ts
feat(metrics): label injection on prometheus metrics to add namespace when it exists
refactor: remove CONDUIT_URL from public runtime config
feat: create utility to inject labels
refactor: all metric components to include label prop
> fix: metrics & logs not correctly queried when on k8s 

- apps/Conduit-UI/src/features/storage/components/StorageConfig.tsx
- apps/Conduit-UI/src/features/storage/models/StorageModels.ts
- apps/Conduit-UI/src/features/storage/store/storageSlice.ts
> feat(storage): make S3 storage generic with endpoint specification

- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/Indexes/IndexCard.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/Indexes/SchemaIndexesDrawer.tsx
- apps/Conduit-UI/src/features/router/components/routerSettings.tsx
- apps/Conduit-UI/src/features/settings/components/GeneralSettingsTab.tsx
> fix(database): unable to set postgres indexes, invalid hash index value

- apps/Conduit-UI/src/features/notifications/components/NotificationConfig.tsx
> feat(push-notifications): basic provider support

- apps/Conduit-UI/src/features/settings/components/SettingsAdmins.tsx
- apps/Conduit-UI/src/features/settings/http/SettingsRequests.ts
fix(settings): admin allowed to try to delete self
fix(settings): wrong endpoint in change other admin pass
fix(settings): admin allowed to try change self pass from table
> fix(settings): admin password and deletion of self

- apps/Conduit-UI/src/features/authentication/components/AuthenticationConfig.tsx
> fix(authentication): config update access/refreshToken expiry using single state

- apps/Conduit-UI/src/components/common/FormComponents/FormInputJsonEditor.tsx
- apps/Conduit-UI/src/components/common/JsonEditorComponent.tsx
- apps/Conduit-UI/src/features/notifications/components/SendNotificationForm.tsx
> feat: Notifications send form data field

- apps/Conduit-UI/src/features/storage/components/StorageConfig.tsx
> feat: allowContainerCreation switch for storage config

- apps/Conduit-UI/src/features/router/components/SecurityTab.tsx
- apps/Conduit-UI/src/features/router/components/UpdateSecurityClient.tsx
- apps/Conduit-UI/src/features/router/store/routerSlice.ts
> feat: security client client id copy to clipboard & fixes

- apps/Conduit-UI/src/features/database/components/custom-endpoints/OperationSection.tsx
- apps/Conduit-UI/src/features/database/components/schemas/Introspection/IntrospectionLayout.tsx
- apps/Conduit-UI/src/features/database/components/schemas/Schemas.tsx
- apps/Conduit-UI/src/features/database/http/CustomEndpointsRequests.ts
- apps/Conduit-UI/src/features/database/http/DatabaseRequests.ts
> fix(database): sort schemas/endpoints by name

- apps/Conduit-UI/src/features/authentication/components/AuthenticationConfig.tsx
- apps/Conduit-UI/src/features/authentication/models/AuthModels.ts
- apps/Conduit-UI/src/features/authentication/store/authenticationSlice.ts
- apps/Conduit-UI/src/features/router/components/routerSettings.tsx
- apps/Conduit-UI/src/features/router/models/RouterModels.ts
- apps/Conduit-UI/src/features/router/store/routerSlice.ts
- apps/Conduit-UI/src/features/settings/components/GeneralSettingsTab.tsx
- apps/Conduit-UI/src/features/settings/models/SettingsModels.ts
- apps/Conduit-UI/src/features/settings/store/settingsSlice.ts
refactor(authentication)!: remove captcha provider settings
feat(router): add captcha providers settings
feat(router,admin): add cors settings
> feat(authentication,router,admin)!: captcha/cors settings

- apps/Conduit-UI/src/features/database/components/schemas/SchemaOverview/SchemaViewer.tsx
- apps/Conduit-UI/src/features/database/components/types/EnumType/EnumForm.tsx
- apps/Conduit-UI/src/features/database/components/types/EnumType/EnumType.tsx
- apps/Conduit-UI/src/features/database/models/BuildTypesModels.ts
> feat: default field for database enum type

- apps/Conduit-UI/src/features/database/components/custom-endpoints/CustomEndpointsLayout.tsx
- apps/Conduit-UI/src/features/database/http/DatabaseRequests.ts
> feat: export and import functionality for database custom endpoints

- apps/Conduit-UI/src/features/database/components/schemas/EditSchema/Header.tsx
- apps/Conduit-UI/src/features/database/components/schemas/SchemaEditor.tsx
- apps/Conduit-UI/src/features/database/models/CmsModels.ts
> feat: authorization database UI

- apps/Conduit-UI/package.json
- apps/Conduit-UI/src/components/modules/Modules.tsx
- apps/Conduit-UI/src/features/router/components/routeGrid.tsx
- apps/Conduit-UI/src/features/router/http/SecurityRequests.ts
- apps/Conduit-UI/src/features/router/routerLayout.tsx
- apps/Conduit-UI/src/features/router/store/routerSlice.ts
- apps/Conduit-UI/src/pages/_app.tsx
- apps/Conduit-UI/src/pages/router/routes.tsx
- yarn.lock
> feat: router graph visualization

- apps/Conduit-UI/src/features/notifications/components/SendNotificationForm.tsx
- apps/Conduit-UI/src/features/notifications/models/NotificationModels.ts
> feat: silent notifications

- apps/Conduit-UI/src/features/database/components/custom-endpoints/EndpointInputs.tsx
> feat: custom endpoint input JSON

- apps/admin/app/(dashboard)/(modules)/push-notifications/settings/page.tsx
- apps/admin/components/notifications/settings.tsx
- apps/admin/components/notifications/settingsForm.tsx
- apps/admin/lib/api/notifications/index.ts
- apps/admin/lib/models/Module.ts
- apps/admin/lib/models/Notification.ts
> feat(notifications): ui and api integration for push notifications

- apps/admin/app/(dashboard)/(modules)/router/settings/page.tsx
- apps/admin/app/(dashboard)/template.tsx
- apps/admin/components/router/settings.tsx
- apps/admin/lib/api/router/index.ts
- apps/admin/lib/models/Router.ts
> Router settings: ui and api integration

- apps/admin/app/(dashboard)/(modules)/storage/settings/page.tsx
- apps/admin/components/notifications/settings.tsx
- apps/admin/components/storage/settings.tsx
- apps/admin/components/storage/settingsForm.tsx
- apps/admin/lib/api/modules/index.ts
- apps/admin/lib/api/notifications/index.ts
- apps/admin/lib/api/storage/index.ts
- apps/admin/lib/models/Storage.ts
- apps/admin/lib/utils.ts
> feat(storage): ui and api integration for storage settings page

- apps/admin/app/(dashboard)/(modules)/forms/settings/page.tsx
- apps/admin/components/forms/settings.tsx
- apps/admin/components/notifications/settings.tsx
- apps/admin/lib/api/forms/index.ts
- apps/admin/lib/api/notifications/index.ts
- apps/admin/lib/models/Form.ts
> feat(forms): ui and api integration for forms settings page

- apps/admin/app/(dashboard)/(modules)/storage/settings/page.tsx
- apps/admin/components/chat/settings.tsx
- apps/admin/components/email/settings.tsx
- apps/admin/components/forms/settings.tsx
- apps/admin/components/functions/settings.tsx
- apps/admin/components/notifications/settings.tsx
- apps/admin/components/router/settings.tsx
- apps/admin/components/sms/settings.tsx
- apps/admin/components/storage/settings.tsx
- apps/admin/components/storage/settingsForm.tsx
- apps/admin/components/storage/zod.ts
- apps/admin/lib/api/authorization/index.ts
- apps/admin/lib/api/chat/index.ts
- apps/admin/lib/api/email/index.ts
- apps/admin/lib/api/forms/index.ts
- apps/admin/lib/api/functions/index.ts
- apps/admin/lib/api/notifications/index.ts
- apps/admin/lib/api/router/index.ts
- apps/admin/lib/api/sms/index.ts
- apps/admin/lib/api/storage/index.ts
- apps/admin/lib/models/Storage.ts
This PR fixes the following:
- Storage config fields
- Storage config Zod schema
- server-side config GET/PATCH API function call type signatures
> fix(admin): Storage config fields/validation, module config API response types

- apps/admin/app/(dashboard)/(modules)/chat/settings/page.tsx
- apps/admin/app/(dashboard)/(modules)/forms/settings/page.tsx
- apps/admin/app/(dashboard)/(modules)/storage/settings/page.tsx
- apps/admin/components/chat/settings.tsx
- apps/admin/components/chat/settingsForm.tsx
- apps/admin/components/forms/settings.tsx
- apps/admin/components/router/settings.tsx
- apps/admin/components/settings/general.tsx
- apps/admin/lib/models/Form.ts
- apps/admin/lib/models/Router.ts
- apps/admin/lib/models/Settings.ts
This PR introduces the following:
- `Core` / `Admin` / `Router` Settings cleanups
- `Forms`: Settings missing Catcha config option with availability check
- `Chat`: Settings config option availability checks for `Email` and `PushNotifications`
> fix(admin): Forms/Chat Settings missing cfg options, dependency availability checks

- apps/admin/app/(dashboard)/(modules)/email/templates/[_id]/page.tsx
- apps/admin/app/(dashboard)/(modules)/email/templates/page.tsx
- apps/admin/components/email/email-editor.tsx
- apps/admin/components/email/templates/createTemplateSheet.tsx
- apps/admin/components/email/templates/dashboard.tsx
- apps/admin/components/email/templates/templateForm.tsx
- apps/admin/components/email/templates/templatePreview.tsx
- apps/admin/lib/api/email/index.ts
- apps/admin/lib/models/email/schemas.ts
- apps/admin/package.json
- yarn.lock
> feat(email): email editor

- apps/admin/app/(dashboard)/(modules)/authentication/strategies/page.tsx
- apps/admin/app/(dashboard)/(modules)/database/models/layout.tsx
- apps/admin/app/(dashboard)/(modules)/database/models/page.tsx
- apps/admin/app/(dashboard)/(modules)/email/send/page.tsx
- apps/admin/app/(dashboard)/(modules)/storage/browse/layout.tsx
- apps/admin/app/(dashboard)/template.tsx
- apps/admin/components/authentication/teams/TeamActionsProvider.tsx
- apps/admin/components/authentication/users/UserActionsProvider.tsx
- apps/admin/components/chat/rooms/dashboard.tsx
- apps/admin/components/database/navigation.tsx
- apps/admin/components/database/tables/columns.tsx
- apps/admin/components/database/tables/data-table.tsx
- apps/admin/components/database/tables/index.tsx
- apps/admin/components/email/templates/dashboard.tsx
- apps/admin/components/notifications/tokens/tokens.tsx
- apps/admin/lib/api/database/index.ts
- apps/admin/lib/models/database/index.ts
- apps/admin/lib/models/database/schemas.ts
> feat(database): layout initial setup

- apps/admin/app/(dashboard)/(modules)/database/models/page.tsx
- apps/admin/components/database/tables/data-table.tsx
- apps/admin/components/ui/pagination.tsx
> feat(database): pagination explicit page/limit selectors
